Unauthenticated Gitlab SSRF - CI Lint API [CVE-2021-22214]
zaproxy/community-scripts pull request #236
Opened 2021-07-27 10:02 UTC by Prince-Mendiratta

#235 - Unauthenticated Gitlab SSRF - CI Lint API [CVE-2021-22214]

Signed-off by: prince.mendiratta@getastra.com

2021-07-27 10:09 UTC, thc202 commented
The DCO check is failing, the commits should be fixed up.

2021-07-29 09:57 UTC, Prince-Mendiratta commented
Updated, please review!

2021-07-29 11:41 UTC, kingthorin requested changes

2021-07-29 11:41 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +var pluginid = 1204616;
This isn't [registered](https://github.com/zaproxy/zaproxy/blob/develop/docs/scanners.md) and can be left out.

2021-07-29 11:41 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +        // A unqiue term in the demo YAML file which will be present in
```suggestion
        // A unique term in the demo YAML file which will be present in
```

2021-07-29 11:41 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +}
This should use the model in the template:
```js
// risk: 0: info, 1: low, 2: medium, 3: high
// confidence: 0: falsePositive, 1: low, 2: medium, 3: high, 4: confirmed
as.newAlert()
	.setRisk(1)
	.setConfidence(1)
	.setName('Active Vulnerability title')
	.setDescription('Full description')
	.setParam(param)
	.setAttack('Your attack')
	.setEvidence('Evidence')
	.setOtherInfo('Any other info')
	.setSolution('The solution')
	.setReference('References')
	.setCweId(0)
	.setWascId(0)
	.setMessage(msg)
```

May as well be done up at 58-73 instead of a secondary method.

2021-07-29 11:41 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +                String(rebody),
Just `"CI_PIPELINE_SOURCE"` instead of jamming unlimited body characters into evidence?

2021-07-29 13:56 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +}
Hi kingthorin;

First of all, thanks for the review.

I will sort the order for the parameters to abide by the template.

I believe that the lines 132-135 are necessary for raising an alert in a targeted script. Should I move those up into the main function itself and remove the `customAlert()` function altogether? Please do let me know if there is a better method.

2021-07-29 14:06 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +}
It's not as much the order as the functionality. You're probably be right, I was treating it as an active rule.

2021-07-29 14:07 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +}
Just looked at some other content, you're right. It would be more like a HttpSender (ex: https://github.com/zaproxy/community-scripts/blob/main/httpsender/Alert%20on%20HTTP%20Response%20Code%20Errors.js) so you've done the right thing for the most part.

As for the plugin ID if it isn't going to be registered I believe you can just pass `0` (zero), to the alert constructor. (@psiinon @thc202 correct me if I'm wrong.)

2021-07-29 14:12 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +}
Ah, no issues. I believe this will be helpful as a reference for raising alerts in targeted scripts since I can't find any already existing.

As for the plugin ID, haha that is the numbering sequence we use internally. However, do let me know if this isn't going to be registered. I'll pass `0` as the plugin ID.

2021-07-29 14:34 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +}
You can open a PR against that scanners.md file, perfectly fine.

2021-07-29 18:37 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +var pluginid = 1204616;
Have sent PR to register for the plugin ID.

2021-07-29 18:37 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +        // A unqiue term in the demo YAML file which will be present in
Resolved.

2021-07-29 19:02 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +            alertEvidence = "Presence of a unique term, [CI_PIPELINE_SOURCE] was detected in the response, which is part of the payload."
- Param is intended to literally be the impacted param (or header field in the case of some passive scripts) If the issues manifests via a simple GET request then there's no param implicated.
- Attack should be the actual payload sent to trigger the issue.
- Evidence should be a string in the request/response which validates or indicates the issue is present, and will be highlighted when someone is looking at alerts in the GUI.

2021-07-29 19:03 UTC, kingthorin commented on targeted/cve-2021-22214.js
>          if (rebody.contains("CI_PIPELINE_SOURCE")) {
These two IFs may as well be combined.

2021-07-29 19:05 UTC, kingthorin commented on targeted/cve-2021-22214.js
> +            alertEvidence = "Presence of a unique term, [CI_PIPELINE_SOURCE] was detected in the response, which is part of the payload."
You could include this "alertEvidence" sentence in "Other Info" (or description) if you feel it will help people.

2021-07-29 19:07 UTC, kingthorin commented
Thanks for that screenshot by the way, that helps make things make more sense. I wasn't aware that GitLab had a private (or personal) hosted solution. (Though I also didn't bother to read up on the CVE you'd quoted 🤷 )

2021-07-29 19:29 UTC, Prince-Mendiratta commented
Ah, Gitlab offers community and enterprise editions that can be hosted privately and many enterprises prefer to manage their codebase through these private gitlab instances. Moreover, there's a high chance this issue might be prevalent on those instances since upgrading Gitlab can prove to be quite a bit of hassle. 😛

2021-07-29 19:51 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +            alertEvidence = "Presence of a unique term, [CI_PIPELINE_SOURCE] was detected in the response, which is part of the payload."
Have modified accordingly.

2021-07-29 19:52 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
>          if (rebody.contains("CI_PIPELINE_SOURCE")) {
Done.

2021-07-30 14:27 UTC, kingthorin approved these changes
Looks good to me

2021-08-02 04:53 UTC, Prince-Mendiratta commented
Hi! @thc202 @psiinon any updates?

2021-08-02 05:51 UTC, thc202 commented on CHANGELOG.md
> +- targeted/cve-2021-22214.js > A targeted script to check for Unauthorised SSRF on Gitlab - CVE 2021-22214
`Gitlab` → `GitLab`, same comment for other occurrences (also pull request title).

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    // Initiate the exploit
Please remove these comments that repeat what the code is doing.

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    var sender = new org.parosproxy.paros.network.HttpSender(org.parosproxy.paros.model.Model.getSingleton().getOptionsParam().getConnectionParam(), true, 6);
Import the classes.

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    var obj = {"include_merged_yaml": true, "content": "include:\n  remote: https://raw.githubusercontent.com/getastra/juice-shop/master/resources/cve-2021-22214.yml"}
It would be better to include the file in this repository.

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +        // confidence: 0: falsePositive, 1: low, 2: medium, 3: high, 4: confirmed
It would be better to keep the variables, given the distance to the actual usage.

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +        var alertAttack = String(exploitResponse.getRequestBody().toString());
Is the cast really needed?

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +	sender.sendAndReceive(newReq);
Replace tabs.

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +	newReq.getRequestHeader().setHeader(org.parosproxy.paros.network.HttpHeader.CONTENT_LENGTH, String(contentLength));
`newReq.getRequestHeader().setContentLength(newReq.getRequestBody().length());`

2021-08-02 05:51 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    ref = new org.parosproxy.paros.model.HistoryReference(org.parosproxy.paros.model.Model.getSingleton().getSession(), 15, msg);
Use the constant for the type.

2021-08-02 06:41 UTC, Prince-Mendiratta commented on CHANGELOG.md
> +- targeted/cve-2021-22214.js > A targeted script to check for Unauthorised SSRF on Gitlab - CVE 2021-22214
Updated.

2021-08-02 06:41 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +    var sender = new org.parosproxy.paros.network.HttpSender(org.parosproxy.paros.model.Model.getSingleton().getOptionsParam().getConnectionParam(), true, 6);
Updated.

2021-08-02 06:41 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +        // confidence: 0: falsePositive, 1: low, 2: medium, 3: high, 4: confirmed
Have added the comments next to function call.

2021-08-02 06:42 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +    var obj = {"include_merged_yaml": true, "content": "include:\n  remote: https://raw.githubusercontent.com/getastra/juice-shop/master/resources/cve-2021-22214.yml"}
Have added the file. However, one of the test seems to be failing. How can I resolve that?

2021-08-02 06:43 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +        var alertAttack = String(exploitResponse.getRequestBody().toString());
Nope. Removed.

2021-08-02 06:43 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +	sender.sendAndReceive(newReq);
Should work now?

2021-08-02 06:43 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +	newReq.getRequestHeader().setHeader(org.parosproxy.paros.network.HttpHeader.CONTENT_LENGTH, String(contentLength));
Updated.

2021-08-02 06:44 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +    ref = new org.parosproxy.paros.model.HistoryReference(org.parosproxy.paros.model.Model.getSingleton().getSession(), 15, msg);
I didn't understand what you meant by this. Some more details, please?

2021-08-02 07:06 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    var obj = {"include_merged_yaml": true, "content": "include:\n  remote: https://raw.githubusercontent.com/getastra/juice-shop/master/resources/cve-2021-22214.yml"}
The file needs to be added to other directory, either top level of the repo or create another one (docs?).

2021-08-02 07:08 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    ref = new org.parosproxy.paros.model.HistoryReference(org.parosproxy.paros.model.Model.getSingleton().getSession(), 15, msg);
`HistoryReference.TYPE_ZAP_USER`. btw, the `ref` variable could be initialised directly.

2021-08-02 07:21 UTC, thc202 commented on CHANGELOG.md
> +- targeted/cve-2021-22214.js > A targeted script to check for Unauthorised SSRF on Gitlab - CVE 2021-22214
This one was not updated.

2021-08-02 07:25 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    // Modify the Request Header
Could be removed.

2021-08-02 07:25 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    // Clone the original request
Could be removed.

2021-08-02 07:25 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    // Change the HTTP method to POST
Could be removed.

2021-08-02 08:01 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +    ref = new org.parosproxy.paros.model.HistoryReference(org.parosproxy.paros.model.Model.getSingleton().getSession(), 15, msg);
Resolved.

2021-08-02 08:01 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +    var obj = {"include_merged_yaml": true, "content": "include:\n  remote: https://raw.githubusercontent.com/getastra/juice-shop/master/resources/cve-2021-22214.yml"}
Have added the file to `resources` directory. I hope that's okay?

2021-08-02 08:11 UTC, thc202 commented on targeted/cve-2021-22214.js
> +var Sender = Java.type("org.parosproxy.paros.network.HttpSender")
`HttpSender`, it's clearer if it matches the class name.

2021-08-02 08:11 UTC, thc202 commented on targeted/cve-2021-22214.js
> +var Session = Model.getSingleton().getSession();
`session`, just an instance.

2021-08-02 08:13 UTC, thc202 commented on targeted/cve-2021-22214.js
> +    var obj = {"include_merged_yaml": true, "content": "include:\n  remote: https://raw.githubusercontent.com/getastra/juice-shop/master/resources/cve-2021-22214.yml"}
`src/main/resources` I would expect (the path in the script needs to be updated accordingly).

2021-08-02 08:14 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +var Session = Model.getSingleton().getSession();
Ah, got it.

2021-08-02 08:14 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +var Sender = Java.type("org.parosproxy.paros.network.HttpSender")
Makes sense

2021-08-02 08:35 UTC, Prince-Mendiratta commented on targeted/cve-2021-22214.js
> +    var obj = {"include_merged_yaml": true, "content": "include:\n  remote: https://raw.githubusercontent.com/getastra/juice-shop/master/resources/cve-2021-22214.yml"}
Updated.

2021-08-03 08:45 UTC, thc202 commented
Fixed up the commits.

2021-08-03 08:45 UTC, thc202 approved these changes

2021-08-03 08:45 UTC, thc202 commented
Thank you!

2021-08-03 10:35 UTC, kingthorin approved these changes
Thanks

2021-08-03 10:36 UTC, merged